repos:
- repo: local
  hooks:
  - id: pytest
    name: pytest
    entry: ./.venv/bin/pytest tests
    language: system
    types: [python]
    pass_filenames: false
    always_run: true
    stages:
    - pre-push
  - id: mypy
    name: mypy
    entry: mypy .
    language: python
    types: [python]
    pass_filenames: false
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.7.4
  hooks:
    - id: ruff
    - id: ruff-format
- hooks:
  - id: commitizen
  - id: commitizen-branch
    stages:
    - pre-push
  repo: https://github.com/commitizen-tools/commitizen
  rev: v3.30.1
